/* Shared module metadata for cross-module suggestions (quiz end screen, etc.) */

const ALL_MODULES = [
  { id: 'playground', title: 'Playground', description: 'Chat directly with AI and experiment with parameters in real time', tag: 'Interactive', tagColor: '#0071E3' },
  { id: 'tokenizer', title: 'Tokenizer', description: 'See exactly how AI reads your text — broken into tokens in real time', tag: 'Visual', tagColor: '#AF52DE' },
  { id: 'generation', title: 'Token Generation', description: 'Watch AI predict the next word live — Manual or Simulate', tag: 'Interactive', tagColor: '#0071E3' },
  { id: 'how-llms-work', title: 'How LLMs Work', description: 'An interactive 5-stage journey from your prompt to the AI response', tag: 'Journey', tagColor: '#FF9500' },
  { id: 'model-training', title: 'Model Training', description: 'Discover how AI models like ChatGPT are built from scratch — data to deployment', tag: 'Journey', tagColor: '#FF9500' },
  { id: 'prompt-engineering', title: 'Prompt Engineering', description: 'Learn how to write better prompts and get dramatically better results from any AI', tag: 'Practical', tagColor: '#34C759' },
  { id: 'context-engineering', title: 'Context Engineering', description: 'Learn how to give AI the right context to get dramatically better results every time', tag: 'Practical', tagColor: '#34C759' },
  { id: 'rag', title: 'RAG', description: 'How AI learns from YOUR documents — Retrieval Augmented Generation explained', tag: 'Journey', tagColor: '#FF9500' },
  { id: 'agentic-ai', title: 'Agentic AI', description: 'AI that plans, acts and learns on its own — understand the systems changing what AI can do', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'machine-learning', title: 'Machine Learning', description: 'How machines actually learn from data — the foundation of all modern AI', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'neural-networks', title: 'Neural Networks', description: 'Watch a neural network learn in real time — animated weights, live loss curves, and hands-on backpropagation', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'deep-learning', title: 'Deep Learning', description: 'Discover the neural networks powering every AI breakthrough — from image recognition to ChatGPT', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'computer-vision', title: 'Computer Vision', description: 'How does AI see a cat and know it\'s a cat? Drag convolution filters over pixel grids, watch feature maps emerge, and build intuition for how CNNs, ResNets, and modern vision transformers actually work.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'fine-tuning', title: 'Fine-Tuning', description: 'Turn a general-purpose AI into a domain expert trained on your specific data and style', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'generative-ai', title: 'Generative AI', description: 'From noise to masterpiece — discover how AI creates images, music, video, code and text that never existed before', tag: 'Journey', tagColor: '#FF9500' },
  { id: 'ai-city-builder', title: 'AI City Builder', description: 'Investigate AI-powered mysteries in a growing city. Solve detective cases using real AI concepts.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'ai-lab-explorer', title: 'AI Lab Explorer', description: 'Walk through an AI research lab. Unlock each room by completing hands-on challenges.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'prompt-heist', title: 'Prompt Heist', description: 'Craft the perfect prompt to outsmart AI security systems and pull off 5 legendary heists.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'token-budget', title: 'Token Budget', description: 'Rewrite prompts to fit strict token limits without losing quality. Real API cost thinking through play.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'ai-ethics-tribunal', title: 'AI Ethics Tribunal', description: 'Preside over real-world AI dilemmas. Weigh the arguments. Deliver your verdict. No easy answers.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'pm-simulator', title: 'PM Simulator', description: 'You are the PM. Write system instructions, design evals, fix hallucinations. Ship the AI feature — or watch it fail.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'ai-native-pm', title: 'AI-Native PM', description: 'The deliverables AI engineers actually need from PMs — system instructions, evals, and structured logic.', tag: 'Professional', tagColor: '#0EA5E9' },
  { id: 'ai-safety', title: 'AI Safety & Hallucinations', description: 'Why AI confidently makes things up — and the practical techniques that stop it.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'ai-fluency', title: 'AI Fluency', description: 'The collaboration habits that separate AI power users from passive ones — backed by real research.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'ai-startup-simulator', title: 'AI Startup Simulator', description: 'You just got funded. Build vs buy, RAG vs fine-tune, which data to collect. Make the right calls or watch your startup fail.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'precision-recall', title: 'Precision & Recall', description: 'Why accuracy is a lie and what to measure instead. Master TP, TN, FP, FN, precision, recall and F1 through interactive real-world scenarios.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'rag-under-the-hood', title: 'Why RAG Fails', description: 'Your RAG works in the demo and breaks in production. Learn exactly why — chunking, metadata, retrieval, filtering — and how to fix each layer.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'ai-in-production', title: 'AI in Production', description: 'Shipping an AI feature is the beginning, not the end. Learn how to monitor quality, measure latency, track cost, detect drift and know when your AI is silently failing.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'alignment-game', title: 'The Alignment Game', description: 'Give an AI a goal. Watch it achieve the goal perfectly and completely miss the point. Can you write constraints tight enough to stop it?', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'choosing-ai-model', title: 'Choosing the Right AI Model', description: 'GPT-5, Claude, Gemini, DeepSeek, Llama — the choice is paralyzing. Learn the framework that cuts through the noise and matches any task to the right model, every time.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'ollama', title: 'Run AI Locally', description: 'No API costs. No data leaving your machine. No rate limits. Learn how Ollama lets you run Llama, Gemma, Mistral and more on your own hardware — and build your own custom AI assistant in minutes.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'label-master', title: 'Label Master', description: 'Draw bounding boxes around objects as fast as you can. Scored on IoU accuracy. Escalates from single objects to crowded scenes to pixel segmentation. Teaches how object detection really works — and why labelling AI training data is so hard.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'draw-and-deceive', title: 'Draw & Deceive', description: 'Draw on a pixel grid. GPT-4o tries to classify what you drew. Try to make it say the right thing — then try to fool it. Teaches how AI vision works and why it sometimes fails spectacularly.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'agent-office', title: 'Agent Office', description: 'Run a pixel art AI startup. Assign agents to tasks, give them tools and instructions, watch them work in real time. Learn why tools, memory, and clear instructions determine everything about whether an AI agent succeeds or fails.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'claude-code', title: 'Claude Code', description: 'Your AI pair programmer that lives in the terminal. Learn how Claude Code reads your codebase, executes real commands, remembers your conventions via CLAUDE.md, and connects to any tool via MCP.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'claude-skills', title: 'Claude Skills', description: 'Skills are reusable instruction files that teach Claude how to do specific tasks better — permanently. Learn how to write a SKILL.md, when to use one, how triggering works, and how to build skills that compound in value over time.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'agent-teams', title: 'Agent Teams', description: 'Subagents are function calls. Agent Teams are organisations. Learn how Claude Code\'s experimental multi-agent feature works: lead agents, teammates, shared task lists, and direct messaging between agents working in parallel.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'custom-agents', title: 'Custom Agents', description: 'Define specialist AI assistants for your own workflow. A security auditor, a test writer, a doc generator — each with its own system prompt, tools, model, and memory. Claude delegates to them automatically. One Markdown file. Infinite leverage.', tag: 'Technical', tagColor: '#5856D6' },
  { id: 'model-training-tycoon', title: 'Model Training Tycoon', description: 'You have $50,000 and 6 weeks. Train the best AI model you can. Allocate budget across data, architecture, training, and fine-tuning. Survive GPU outages, bad labels, and rival model drops.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'system-design-interview', title: 'System Design Interview', description: 'Design a real AI system across 7 architecture decisions. Two interviewers push back on every choice. Then your design faces three live incidents. Three scenarios, all replayable.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'spec-driven-dev', title: 'Spec-Driven Development', description: 'Stop vibe coding. Start speccing. Write what you want before AI writes how to build it. Learn the three-document pattern that turns chaotic AI sessions into structured, reviewable, reproducible builds.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'ai-coding-tools', title: 'AI Coding Tools', description: 'Cursor, Copilot, Windsurf, Kiro, Cline — the market is exploding. This tour covers the 8 tools every developer needs to know, how they differ, and a quick quiz that recommends the right one for your workflow.', tag: 'Practical', tagColor: '#34C759' },
  { id: 'ai-pm-workflows', title: 'AI-Native PM Workflows', description: 'The prompts, templates and weekly rhythms that separate AI-native PMs from everyone else. Copy-ready prompts for discovery, planning and stakeholder communication.', tag: 'Professional', tagColor: '#0EA5E9' },
  { id: 'prompt-injection', title: 'Prompt Injection Explained', description: 'The number one AI security risk according to OWASP 2025. Learn how attackers hijack AI systems using nothing but carefully crafted text — then try the attacks yourself in a live simulation.', tag: 'Security', tagColor: '#EF4444' },
  { id: 'prompt-injection-lab', title: 'Prompt Injection Lab', description: 'Choose your side. As the attacker, extract secrets using real injection techniques. As the defender, write the system prompt that stops those exact attacks. Both roles teach you something the other cannot.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'skill-builder-challenge', title: 'Skill Builder Challenge', description: 'Claude fails at a task. Your job: write the SKILL.md that fixes it. Three rounds, escalating complexity. See your skill run against real test cases.', tag: 'Game', tagColor: '#F59E0B' },
  { id: 'image-generation', title: 'Image Generation', description: 'How does AI turn a text prompt into a photorealistic image? Follow the diffusion process step by step — from pure random noise through dozens of denoising passes guided by your words.', tag: 'Journey', tagColor: '#FF9500' },
]

export function getRandomModules(excludeId, count = 3, hiddenIds = new Set()) {
  const others = ALL_MODULES.filter((m) => m.id !== excludeId && !hiddenIds.has(m.id))
  const shuffled = others.sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export default ALL_MODULES
